### ISSUE TITLE
Unable to authenticate JWT Web token to access content using Postman Test 

### ISSUE THREAD

**Issue by pkini2002** [pkini2002/JWT-Authentication-SpringBoot#1]
I was trying to test my API using Postman in order to fetch the data at the endpoint `localhost:8081/home/user`. I was able to fetch the data manually with the help of the browser by authenticating myself to the route `localhost:8081/login`.

<br>

But while testing my API with the help of JWT I get this log in the terminal of IntelliJ

```
2023-09-24T12:58:48.662+05:30  INFO 6896 --- [nio-8081-exec-3] o.s.web.filter.OncePerRequestFilter      :  Header :  null
2023-09-24T12:58:48.663+05:30  INFO 6896 --- [nio-8081-exec-3] o.s.web.filter.OncePerRequestFilter      : Invalid Header Value !! 
```

The JWT token is getting created successfully but I am facing a problem while authenticating users using the JWT Token `Authorization: Bearer <JWT Token>`

I have attached the screenshot below along with the error message 
<br>
<img width="726" alt="Screenshot 2023-09-24 125906" src="https://github.com/pkini2002/JWT-Authentication-SpringBoot/assets/84091455/47593f29-2235-406d-881b-425800d5615d">

<br><br>
<img width="730" alt="Screenshot 2023-09-24 125928" src="https://github.com/pkini2002/JWT-Authentication-SpringBoot/assets/84091455/f7c90308-aa07-4a9c-80c0-65895d75ef41">

### Things I have tried so far

-  Recreated JWT by sending a new request
-  Skimmed through the code for any bugs
-  Opened a new HTTP Request in Postman 
-  Tried creating JWT Token with a new admin user
-  Stopped the server and reran the project again

**Comment by DavidOtero91** [comment]
In the second screenshot, the Authorization parameter is in the request body and it should be in the header.

**Comment by pkini2002** [comment]
Oh yes, thanks for pointing it out!
